# Generated by Django 3.1.7 on 2021-04-05 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExpenses', '0004_auto_20210405_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
        ),
    ]
